### ISSUE TITLE
ENS Caching

### ISSUE THREAD

**Issue by Rakowskiii** [WalletConnect/rpc-proxy#107]
- [x] Draft ENS Caching docs
- [x] Consult draft version
- [x] Brainstorm the solution on team meeting
- [ ] Implement simple Caching
- [ ] Implement additional logic 
```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/rpc-proxy/issues/181
- [ ] https://github.com/WalletConnect/rpc-proxy/issues/182
- [ ] https://github.com/WalletConnect/rpc-proxy/issues/191
- [x] ENS caching
```
